version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672" # rabbitMQ AMQP port
      - "15672:15672" # admin management port
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123!@#
